[package]
name = "programs_starter"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["tokio"] }
tokio = { version = "1.0", features = ["time"] }
rfd = "0.14"